### ISSUE TITLE
locale detection per episode

### ISSUE THREAD

**Issue by valvin1** [qtwyeuritoiy/peppercarrot-reader#3]
Don't know if you have been awared of it but there a episode.json file here : https://www.peppercarrot.com/0_sources/episode.json
which contains interesting information to detect episodes and locales per episode.

**Comment by qtwyeuritoiy** [comment]
Hi! lThanks for opening an issue.

Yes, I am aware of the list(_I_ suggested the format), and the feature is on the to-do list.(getPreferredLanguage() in nightlock.peppercarrot.utils in develop branch)

There's an issue, however, that the language code P&C uses is not compatible with the standard ISO language code, which Android provides. I'll probably end up suggesting another file for that :P

So yeah, please stay tuned!

**Comment by qtwyeuritoiy** [comment]
With recent commit this issue is fixed.
